### ISSUE TITLE
Couldn't fetch access token for Github application

### ISSUE THREAD

**Issue by dguettler** [barecheck/code-coverage-action#172]
Hi,

I followed the instructions, created a token, made it available as a secret in the application, but I'm running into this error 
```
(node:6456) UnhandledPromiseRejectionWarning: Error: Couldn't fetch access token for Github application. Check if you use the correct `BARECHECK_GITHUB_APP_TOKEN`
    at createGithubAccessToken (/actions-runner/_work/_actions/barecheck/code-coverage-action/v0.6.1/dist/index.js:11291:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createNewAccessToken (/actions-runner/_work/_actions/barecheck/code-coverage-action/v0.6.1/dist/index.js:11011:21)
```

Any idea what is going wrong here?

Thank you.

**Comment by vitaliimelnychuk** [comment]
Hello @dguettler!

I am sorry for the issue we have with that version of barecheck. Can you please update barecheck github action to v1?

Like here: `barecheck/code-coverage-action@v1`. I will update all docs to use proper version.

**Comment by dguettler** [comment]
Hi,

I updated the version, now the error changed to
```
Error: Couldn't fetch accessToken token by using apiKey. Check if you use
the correct `API_KEY`
```
Do I need to change the environment secret name?

Thanks, Daniel

**Comment by vitaliimelnychuk** [comment]
Thanks for your feedback @dguettler. 

I am sorry you have faced those problems with action. 

I already fixed the issue here https://github.com/barecheck/code-coverage-action/pull/175. You don't need to update anything, just run your workflow once more and it should pass and post a comment. 

You always are able to use https://www.barecheck.com/ to store results and make comparison with previous executions but it's not required. 

Let me know if you still experiencing any issues.

**Comment by vitaliimelnychuk** [comment]
Hello @dguettler!

Do you still have the issue with action after running action one more time?

**Comment by andrey-sheremeta** [comment]
Hi @vitaliimelnychuk.

Thanks a lot for a great job.

I also faced the similar issue. we used v.0.51 for a while, but the last week it stopped posting the summary commit, after upgrading to v1 (`barecheck/code-coverage-action@v1`), it throws the error
```
Error: Couldn't fetch accessToken token by using appToken. Check if you use the correct `BARECHECK_APP_KEY`
```
![image](https://user-images.githubusercontent.com/70937584/168554522-0cc79074-4681-4b86-9b5c-7a34473f0e62.png)

I tried to rerun the job several times, but it did not help. 

Could you please help with this?

**Comment by vitaliimelnychuk** [comment]
Hello @andrey-sheremeta!

I released v1 as a stable version and will deprecate all previous releases soon. I am sorry that you faced the issue with the old version.

Can you please try to uninstall and install the application again to get a new token to post comments?

If it will not help please send here your config of the action. I am more than happy to fix the issue you're facing.

**Comment by dguettler** [comment]
No the action did run thank you. I think though that it doesn’t do anything
unless I also provide a base coverage report. Is this assumption correct?

**Comment by vitaliimelnychuk** [comment]
Hello @dguettler!

If you don't have the base coverage report passed it should still post a comment with all uncovered lines but without the comparison part.

It usually helps to pass base coverage reports or use Barecheck cloud to have diff in percentages.

**Comment by dguettler** [comment]
Hi @vitaliimelnychuk 

this is what I currently get in the logs
```
Run barecheck/code-coverage-action@v1
  with:
    barecheck-github-app-token: ***
    lcov-file: coverage/lcov.info
    show-annotations: warning
lcov-file: coverage/lcov.info
Current code coverage: NaN%
Base branch code coverage: 0%
Code coverage diff: NaN%
Code coverage diff: NaN%
minimum-ratio: NaN
minimum-ratio is disabled for this workflow
Show annotations feature enabled
```
There is no comment, but I'm also just testing this on a PR which only adds the check. So not sure if this is or isn't the expected outcome.

**Comment by dguettler** [comment]
This is on a 2nd project
```
Run barecheck/code-coverage-action@v1
  with:
    barecheck-github-app-token: ***
    lcov-file: ./osl.info
    show-annotations: warning
lcov-file: ./osl.info
Current code coverage: [3](https://github.com/physion/ovation-apps/runs/6198512632?check_suite_focus=true#step:2:3)3.99%
Base branch code coverage: 0%
Code coverage diff: 33.[9](https://github.com/physion/ovation-apps/runs/6198512632?check_suite_focus=true#step:2:9)9%
Code coverage diff: 33.99%
minimum-ratio: NaN
minimum-ratio is disabled for this workflow
Show annotations feature enabled
```
again, no comment. Only change in the PR is adding the actions to run the check.

**Comment by vitaliimelnychuk** [comment]
Hello @dguettler!

Maybe you can also try to uninstall/install Barecheck application to make sure that token is valid.

**Comment by vitaliimelnychuk** [comment]
Hey @andrey-sheremeta!

It's really weird. I just added PR to test https://github.com/barecheck/code-coverage-action/pull/184 and it looks fine, not sure what is different on your side. I also did regenerate a token and updated secret with a new one? 

You've got the token from here, right?

<img width="1489" alt="Screenshot 2022-05-19 at 09 14 39" src="https://user-images.githubusercontent.com/22550335/169246108-8e283ce9-efdc-484e-803f-05f0ab472ace.png">

**Comment by andrey-sheremeta** [comment]
yes, right. we removed and installed the app several times but it did not help. also, we found the [`sematic pull request`](https://github.com/zeke/semantic-pull-requests) stopped working for some reason as well. we think the problem is somewhere in our repo settings, so we will try to fix this issue by ourselves. 

thanks a lot for the help.

**Comment by vitaliimelnychuk** [comment]
@andrey-sheremeta Sure, let me know if you will need any help. This is really weird that you have this access issue. 
Maybe, check if your secrets are passed properly.

**Comment by dguettler** [comment]
Wait, I have the barecheck-github-app-token configured, but it’s looking
for barecheck-api-key, where is this one coming from?

**Comment by vitaliimelnychuk** [comment]
Hello @dguettler! Hope you're doing well.

`barecheck-github-app-token` - Barecheck application token, received after application installation comment. Basically, this one is just to give access to the Barecheck GitHub application to post comments. You can receive this token after installing the application as I mentioned in the comment above https://github.com/barecheck/code-coverage-action/issues/172#issuecomment-1131383551

`barecheck-api-key` - Your project API_KEY generated from https://barecheck.com/. Use this property to avoid running coverage for the base branch. This is an optional field, but some people find it useful to use to avoid rerunning coverage for the base branch and keep historical data stored in Barecheck. 

Let me know if this works for you

**Comment by aodhgan** [comment]
@andrey-sheremeta did you ever resolve this? having the same issue

**Comment by vitaliimelnychuk** [comment]
Hello @aodhgan, 

I am not still aware with what exactly we're having issue here. 

If you look into my comment above about using different tokens, what is the one you're using? if it's `barecheck-api-key`, did you try to regenerate it?
